### ISSUE TITLE
Connect frontend to photos api

### ISSUE THREAD

**Issue by jens-peterolsson** [Etimo/photo-garden#15]

**Comment by JohanHazelius** [comment]
-	User can log in via google drive to access his/her personal account through any web browser
-	User can select data sources from which he/she wants to access photos
-	User can access and see all his/her photos from selected sources (=Drive) 
-	User can filter to find photos based on date 
-	User can see photo in preview (pop-up)

**Comment by indrif** [comment]
Read from rest api
