### ISSUE TITLE
API Gateway

### ISSUE THREAD

**Issue by EtimoOscarNylander** [Etimo/photo-garden#19]
Some thoughts from the subway: Should we have one unified API Gateway for the project, and as such letting this API Gayeway be the only API exposed to the internet?

I'm sure you've worked with API Gateways before, and understand their purpose. This will also be relevant in how we set up things like DNS later, so we should determine whether we want one early.

If we decide to create one, we need to:

- Set up a milestone for the API Gateway
- Set up issue for various subtasks related to the API Gateway

**Comment by indrif** [comment]
Reverse proxy
