### ISSUE TITLE
Fix deployment for new structure

### ISSUE THREAD

**Issue by indrif** [Etimo/photo-garden#34]

**Comment by indrif** [comment]
Automate creation of new repositories in ecr.

Also make sure we can build even though there are no previous builds and/or latest

**Comment by indrif** [comment]
Sync repositories if we change name of apps.

**Comment by teozkr** [comment]
Images are now being pushed to ECR again, so I just need to sort out the Kubernetes services.

**Comment by teozkr** [comment]
Gateway is being deployed to Kube again, working on web-frontend.
