### ISSUE TITLE
Logo Proposal for photo-garden

### ISSUE THREAD

**Issue by zuurw** [Etimo/photo-garden#68]
Hi, my name is Zuur. I'm a graphic designer and I'd like to collaborate on your open source project and propose free logo/icon design for your project. If it's something you're interested in, please, let me know!
Best Regards
Zuur

**Comment by JassyrBravo** [comment]
Hi @zuurw !

We are interested, can you send us a mail to kontakt@etimo.se

Best regards!

J.O.

**Comment by zuurw** [comment]
Sorry for the delay in answering, but I had some personal problems to solve and I did not have much time to focus on the projects in github. But now I'm back.

**Comment by zuurw** [comment]
Hi @JassyrBravo 
Sorry for the late reply, but I had some ploblems to resolve.
Now Im ready to work in your project if you still want.

Greetings
